### ISSUE TITLE
函数生成规则

### ISSUE THREAD

**Issue by heimanba** [devsapp/function#1]
假设我们的s.yml配置为
```
edition: 1.0.0
access: simple_mvc
region: cn-hangzhou

services:
  start-function:
    component: ${path(..)}
    props:
      functionPath: src
      app:
        name: functionApp
        runtime: nodejs12
        memory: 1152
        timeout: 60
        concurrency: 1
      http:
        - route: /
        - route: /like
      oss:
        - route: /zip-file
```
在src的目录中: 执行 s init function的时候
有以下目录
```
- src
  - http
      - index
        - config.yml
        - index.js 
      - like
         - config.yml
         - index.js
  - oss
       - zip-file
          - config.yml
          - index.js
```
函数的配置规则为:
1. 函数路径, s.yml映射比如 
```
http
 - /
 - /like
```
codeUrl: 映射路径为 `http/index` 和`http/like`。
2. 函数名
规则为 {事件类型}-{路径名}
3. 函数基本配置:
来自`s.yml`中的app(可以简单映射为函数计算的service的概念，但是把函数公共的配置提取出来了)
4. config.yml
用于函数个性化配置的，优先级高于s.yml中的配置。存在冲突时候，优先使用config.yml中配置
5. 触发器
触发器的配置和函数相同, config.yml优先于s.yml。触发器基本的角色等底层fc-deploy处理掉

6. 动态配置(重要)
假设这样的场景:
- 触发器默认给的权限不足
-  函数作为粘合剂和其他产品进行交互，函数没有执行权限....
这里我们当然可以在配置文件中，让用户手动指定权限等。当时RAM权限和角色一般的用户都非常难以理解。(一般2天之内都理解不了)。但是我们又不能随便给用户授予一个大的权限或者全集合的权限，这样太不安全了。其实所有的需要用到的权限。用户的代码中都会体现出来。所以是不是可以实现智能的分析权限等。然后帮用户把权限给加上?
